### ISSUE TITLE
Repeated computation in DeRhamSequence::ComputeCoarseTracesWithTargets()

### ISSUE THREAD

**Issue by delyank** [LLNL/parelag#12]
This loop:
https://github.com/LLNL/parelag/blob/0f85bff835945749005ea32a70f1c2395927b3a3/src/amge/DeRhamSequence.cpp#L1792
computes among other things coarse local mass matrices and local coarse bases for the trace spaces.

Then, this loop:
https://github.com/LLNL/parelag/blob/0f85bff835945749005ea32a70f1c2395927b3a3/src/amge/DeRhamSequence.cpp#L1990
seems to repeat at least the computation of the coarse local mass matrices again.

Also, the parts (2 lines each) for the projection operator:
https://github.com/LLNL/parelag/blob/0f85bff835945749005ea32a70f1c2395927b3a3/src/amge/DeRhamSequence.cpp#L1894
and
https://github.com/LLNL/parelag/blob/0f85bff835945749005ea32a70f1c2395927b3a3/src/amge/DeRhamSequence.cpp#L2042
seem identical

I think that the second loop 
https://github.com/LLNL/parelag/blob/0f85bff835945749005ea32a70f1c2395927b3a3/src/amge/DeRhamSequence.cpp#L1990
need to be deleted completely from the code.

As a side note, `DeRhamSequence::ComputeCoarseTracesNoTargets()` doesn't seem to exhibit such a repetition.

My question is if I understand this correctly or there is some minor thing that needs the second loop on line `DeRhamSequence.cpp:1990`?

**Comment by barker29** [comment]
So it's been a while, but I believe the code is functionally correct (though its organization, documentation, etc. is obviously a disaster). The first loop you refer to starting at line 1792 acts on local agglomerated elements (AEs) owned by the current processor (see line 1794). Then something is communicated and stored in `P_` in lines 1980-1988. 

Then finally, the second loop you reference starting at line 1990 only acts on AEs that are shared but not owned by the current processor (line 1992). In particular, it reads this communicated `P_` (line 2010) but this would not have been available in the previous loop.

Does this make sense?

**Comment by uvilla** [comment]
Hi Andrew,

I looked at the code, and I agree with your explanation.

The code as is is also computationally optional.
To orthogonalize the targets one need to compute the fine grid mass matrix
restricted to each agglomerate. Then, for agglomerates which are owed by
the processors it makes sense to compute the coarse mass matrices directly
inside the loop (to avoid recomputing the fine grid mass matrix restricted
to the agglomerate).

Regarding the loop in line 1990, we could have possibly directly
communicated the coarse local mass matrices (computed on a different
processor) rather than recomputing them using RAP. However, I don’t think
we have any code handy to perform those communications.

Cheers,

Umbe

**Comment by delyank** [comment]
Thank you, @barker29 and @uvilla! It makes perfect sense now. It seems that I somewhat misread the if statements in the for loops.

It makes sense to communicate the basis traces (prolongator portions), as they are also needed elsewhere, and from there obtaining the coarse element matrices is easily done locally.
